### ISSUE TITLE
Problem with owncloud Rss

### ISSUE THREAD

**Issue by Punkado** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#14]
Hello,

I am to use the Rss feed of the activity of the Owncloud and i can not make it work, i get the error:

2016-07-07 17:09:48,773 - Error fetching feed https://myowncloud/owncloud/apps/activity/rss.php?token=ItecZUeIZQS9aIwuIV3ly46
2016-07-07 17:09:48,783 - <type 'exceptions.KeyError'>
Traceback (most recent call last):
  File "./feedfetcher.py", line 63, in <module>
    feed.Description = d['entries'][0]['description']
  File "/home/Rss-Atom-Feed-Integration-for-Mattermost/env/local/lib/python2.7/site-packages/feedparser.py", line 356, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'description'

I already tried to False for the description  in the settings.py and i have the same problem...

I also tested with other feeds, and works.

Any directions for me?

Thanks so much

**Comment by axelrose** [comment]
Without seeing the feed delivered from owncloud I would just guess that the return feed data doesn't contain a required _description_ item!?

HTH, Axel.

**Comment by Punkado** [comment]
Yes, look like the feed have no description, all the information is in the title:

<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>Activity feed</title>
<language>en</language>
<link>
https://myonwcloud/owncloud/apps/activity/rss.php
</link>
<description>Personal activity feed for admin-user</description>
<pubDate>Thu, 07 Jul 2016 17:54:11 +0000</pubDate>
<lastBuildDate>Thu, 07 Jul 2016 17:54:11 +0000</lastBuildDate>
<atom:link href="https://myonwcloud/owncloud/apps/activity/rss.php" rel="self" type="application/rss+xml"/>
<item>
<guid isPermaLink="false">42</guid>
<title>You deleted New Document.odt</title>
<link>https://XXX.XXX.XXX.XXX/owncloud/apps/files/?dir=/</link>
<pubDate>Sun, 12 Jun 2016 21:41:12 +0000</pubDate>
</item>
<item>
<guid isPermaLink="false">41</guid>
<title>You deleted Photos</title>
<link>https://XXX.XXX.XXX.XXX/owncloud/apps/files/?dir=/</link>
<pubDate>Sun, 12 Jun 2016 21:41:10 +0000</pubDate>
</item>
<item>
<guid isPermaLink="false">40</guid>
<title>You deleted Documents</title>
<link>https://XXX.XXX.XXX.XXX/owncloud/apps/files/?dir=/</link>
<pubDate>Sun, 12 Jun 2016 21:40:53 +0000</pubDate>
</item>
<item>
<guid isPermaLink="false">38</guid>
<title>email@riseup.net changed testeedicao.odt</title>
<link>https://XXX.XXX.XXX.XXX/owncloud/apps/files/?dir=/</link>
<pubDate>Sun, 12 Jun 2016 20:01:33 +0000</pubDate>
</item>
<item>
<guid isPermaLink="false">37</guid>
<title>You created New Document.odt</title>
<link>https://XXX.XXX.XXX.XXX/owncloud/apps/files/?dir=/</link>
<pubDate>Sun, 12 Jun 2016 20:00:21 +0000</pubDate>
</item>

</channel>
</rss>

There any way to ignore the description and just post the Title?

Thanks

**Comment by Punkado** [comment]
Solved change the code of the bot to ignore the description.

Thanks
