### ISSUE TITLE
Defaults not being used for feeds in config

### ISSUE THREAD

**Issue by tejasbubane** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#28]
Code: https://github.com/bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost/blob/master/settings.py.sample#L39-L65

There is `default_show_name`, `default_show_title`, etc. and there are `show_name`, `show_title` values in the `RssFeed` initializer below. While configuring I assumed the default values would be used so I remove the ones from `RssFeed` initializer and the code fails with the error:

```
TypeError: __init__() takes exactly 10 arguments (6 given)
```

I think the default values are not being used.

**Comment by Okhoshi** [comment]
The defaults are used in other situations than the one you are trying (RssFeed created from environment variables with the [Docker Settings](https://github.com/bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost/blob/master/settings.py.docker) or created through the Slash command).

The defaults are not supposed to be used during standard initialization.

**Comment by tejasbubane** [comment]
Can we create a custom constructor which uses those defaults instead of using `RssFeed (..)`?
If not feel free to close this.

**Comment by Okhoshi** [comment]
I don't quite understand the added value with this constructor ? 

You could just call the normal one with all the values.
Or as the configuration file is just plain python, you could create a fonction that return a new RssFeed by calling the constructor with the default values for you.

For me, we can close this.
@dbanck, @elpatron68 Any thoughts ?

**Comment by elpatron68** [comment]
To be honestly, I don´t really understand the problem @Okhoshi, feel free to close this.
