### ISSUE TITLE
web.incoming_webhook.channel.app_error when starting docker container

### ISSUE THREAD

**Issue by starmagoo** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#31]
Hey! I get ths error when I try to start the docker container.

`mattermost-rss_1  | 2017-11-15 16:49:27,593 - Starting new HTTPS connection (1): mattermost.majaonline.de
mattermost-rss_1  | 2017-11-15 16:49:27,611 - "POST /hooks/fp9m3hnkrbbgjcidotj9reeufc HTTP/1.1" 404 178
mattermost-rss_1  | 2017-11-15 16:49:27,612 - Encountered error posting to Mattermost URL https://***/hooks/fp9m3hnkrbbgjcidotj9reeufc, status=404, response_body={u'status_code': 404, u'message': u'Der Kanal konnte nicht gefunden werden', u'request_id': u'sp8woy9kdjfzbkhhwk5r11ej8y', u'id': u'web.incoming_webhook.channel.app_error', u'detailed_error': u''}
`

The incoming hooks works great when I test it with curl.

Any Ideas?

**Comment by elpatron68** [comment]
Hi @starmagoo , I started this project, but the docker part is mostly from @Okhoshi , so I´m not sure about the solution for your problem.

As I see it, there is a problem with the configured Mattermost Channel. Did you configure a webhook for your channel? Is it configured in `settings.py` and does your feed configuration contain the correct channel name?

```
# Your feeds come here:
# RssFeed('Feed name', 'Feed URL', 'Image URL', 'Mattermost username', 'Mattermost channel',
# show name, show title, show description, show url)
```

**Comment by starmagoo** [comment]
Hi @elpatron68 , yes I configured the docker-compose.yml file. settings.py.docker refers to the variable in settings.py. As you can see in my error message the shown URL refers to the webhook URL which I had configured in Mattermost. The webhook works fine, I have tested it with the curl command described here (https://docs.mattermost.com/developer/webhooks-incoming.html).

**Comment by Okhoshi** [comment]
Hi @starmagoo,

It seems it's a configuration problem. 
What did you changed in the compose file ? You normally just have fill in the blanks and change the default channel name. And fill the feeds.env file to get defaults feeds to start with.

Could you share your docker-compose and feeds.env (after removing sensitive informations of course :) ) ?

**Comment by starmagoo** [comment]
Ok I changed MATTERMOST_HOOK_URL, MATTERMOST_CMD_TOKEN, INTEGRATION_LISTENING_PORT and MATTERMOST_CHANNEL.

After that I try to start the container and receive the following error:
`ERROR: Named volume "feeds.env:/code/feeds.env:rw" is used in service "mattermost-rss" but no declaration was found in the volumes section.`

Thereupon I commented out the env_file variable.

**Comment by Okhoshi** [comment]
Ok, and how do you get feeds then ? Instead of commenting the line, try to copy the feeds.env.sample to feeds.env ?

**Comment by starmagoo** [comment]
When I copy the feeds.env.sample to feeds.env I get the Error:

`ERROR: Named volume "feeds.env:/code/feeds.env:rw" is used in service "mattermost-rss" but no declaration was found in the volumes section.`

There is a "Test" Feed inside but the server does not start.

**Comment by Okhoshi** [comment]
Try with ./feeds.env:/code/feeds.env:rw

If it doesn’t work, you can remove that line, it serves another purpose.

**Comment by starmagoo** [comment]
That worked, thanks a lot!
Now I get the first error.

**Comment by Okhoshi** [comment]
Ok. So I suppose that the channel that you set in the compose file exists on your Mattermost instance ? Be sure to use the channel slug and not the channel name.

**Comment by starmagoo** [comment]
Yes Channel exists and I use the spelling from the URL (lowercase).
What do you mean by channel slug?

**Comment by Okhoshi** [comment]
The slug is indeed the channel part of the url, so it’s ok. Mmh that’s really weird...

The Mattermost server is accessible from inside the Docker container ?
Do you have access to some Mattermost logs, in the System Console ?

**Comment by starmagoo** [comment]
How can I try?
I can access from my server to the IP-Adress of both server. I switch the webhook URL from an external URL to a internal IP. But it gets the same error. In the feed container is now ping command installed.

**Comment by starmagoo** [comment]
rss-test is definitely the wrong channel! I don't know where it comes from. The feeds. env is empty except for one entry.

**Comment by Okhoshi** [comment]
`rss-test` is the channel used in the settings.py.sample file. And that's weird that this file is used instead of the feeds.env file.

You didn't change anything to the settings.py.* files ?

**Comment by starmagoo** [comment]
I have checked out git completely new, switched the docker-compse.yml with my entries and the error remains.

**Comment by starmagoo** [comment]
I got it! Removed the whole images (docker rmi ...) and it's running. I guess I changed something in the files and this was in the image.

**Comment by Okhoshi** [comment]
Glad to read that you solve the issue ! 👍 
I close this so.

**Comment by starmagoo** [comment]
Many thank for your help.

**Comment by starmagoo** [comment]
@Okhoshi , how can I pull new news? I can see them in the Mattermost log but not in the channel.
