### ISSUE TITLE
Error in env file

### ISSUE THREAD

**Issue by drallgood** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#33]
I discovered an issue with the feeds.env file which essentially stops new feed entries from being posted when you restart the docker container.

The error is here:
https://github.com/bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost/blob/9d8fab24ba473bdedec5c6c5d3d50bf032a4e68e/rssfeed.py#L45

This is missing a column for the username, which results in the channel name being used as a username und the channel being either `True` or `False`. Obviously that doesn't work and mattermost returns an error `Couldn't find the channel`.

Here's the logic that parses the file:
https://github.com/bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost/blob/86368e1de824779bf9f34ba1d129611fd12b1508/settings.py.docker#L56

Not sure how exactly to fix this, but adding an extra `;` to my feed definitions fixed it for now.

**Comment by drallgood** [comment]
For reference, here's a feed entry (all entries were created using the slash command):
`RSS_FEED_TheLoop='http://loopinsight.com/feed;;news;False;True;True;False'`

**Comment by Okhoshi** [comment]
Hello @drallgood, Thanks for your feedback.

Could you test the change in the PR #34 and report if this is fixed or not ?

**Comment by drallgood** [comment]
Works @Okhoshi 
Thanks!

**Comment by Okhoshi** [comment]
#34 merged.

I close the issue.
