### ISSUE TITLE
Possible error in docker-compose.yml.sample

### ISSUE THREAD

**Issue by clanzett** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#36]
In my opinion there is a "./" missing in the volume section of the docker-compose.yml.sample. 

Your code:
- feeds.env:/code/feeds.env:rw

Working:
- ./feeds.env:/code/feeds.env:rw

Or am i missing something? ;-)

best regards

**Comment by drallgood** [comment]
That may be possible. I'm using a global docker-compose file, so this may or may not be correct

**Comment by Okhoshi** [comment]
@clanzett You're right, currently we're trying to use a container names 'feeds.env'.

**Comment by Okhoshi** [comment]
Thanks for your report @clanzett ! :)
