### ISSUE TITLE
[RFE] persist feeds added with slash command

### ISSUE THREAD

**Issue by sblaisot** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#38]
Hi,

First of all, thanks for this great piece of software.

You can add a feed with the slash command, but this is not persisted in the configuration file or elsewhere so each time the rss bot is restarted, you loose the feeds you added.

Could it be possible to persist them in some way ?

**Comment by sblaisot** [comment]
Actually, it is correctly persisted in `feeds.env` if this file exists but it seems that this file is not even read at startup

**Comment by sblaisot** [comment]
I finally managed to read feeds.env on startup by putting this in my `settings.py` file instead of the standard feed definition:

```
content = []
with open("feeds.env") as f:
    for line in f:
        name, val = line.partition("=")[::2]
        content.append((name, val.strip("\n'")))

feeds = [RssFeed(
                k.replace('RSS_FEED_', ''),
                v.split(';')[0],
                v.split(';')[1] if v.count(';') >= 1 else integration_bot_img,
                v.split(';')[2] if v.count(';') >= 2 else integration_bot_name,
                v.split(';')[3] if v.count(';') >= 3 else default_channel,
                v.split(';')[4] == 'True' if v.count(';') >= 4 else default_show_name,
                v.split(';')[5] == 'True' if v.count(';') >= 5 else default_show_title,
                v.split(';')[6] == 'True' if v.count(';') >= 6 else default_show_description,
                v.split(';')[7] == 'True' if v.count(';') >= 7 else default_show_url)
        for k,v in content if k.startswith('RSS_FEED_')]
```

maybe you can update the settings.py.sample to explain that to new users?

**Comment by Okhoshi** [comment]
In fact, the part reading the `feeds.env` file is in `settings.py.docker` file, as the `feeds.env` method is coming from the docker running mode.

But you're right, we can either update the `settings.py.sample` or create a new sample `settings.py` using the `feeds.env`
