### ISSUE TITLE
authenticated sites

### ISSUE THREAD

**Issue by mihai-satmarean** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#6]
Hello,
very nice and easy to use.
Are there any possibilities to use it for authenticated sites?

Thank you!

**Comment by dbanck** [comment]
What do you mean by authenticated sites? HTTP Auth? Do you have an example?

**Comment by mihai-satmarean** [comment]
I mean that we would like to receive rss from our Jira, or from other sites
that we need to authenticate.

2016-01-14 21:42 GMT+01:00 Daniel Banck <notifications@github.com>:

**Comment by dbanck** [comment]
Jira feeds are protected by basic authentication. So crafting an url containing username and password should work.

Example: `http://user:pass@example.org/docs/examples/basic_auth.xml`

**Comment by mihai-satmarean** [comment]
Great! I'll try that.
Thanks!
