### ISSUE TITLE
Configuring several channels.

### ISSUE THREAD

**Issue by axelrose** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#8]
Hi there!

I just like to ask for a specific configuration:
If I have several different channels with according different webhook urls - how can I configure this with a single installation within `settings.py`?

The sample just has one webhook url in `mattermost_webhook_url` and seemingly aggregates one or more RSS feeds into that.

I wouldn't mind just a duplicate Rss-Atom-Feed-Integration-for-Mattermost installation if there is no other way.

Thanks a lot, Axel.

**Comment by elpatron68** [comment]
Moin Axel,

this integration suports only one configured channel. If you want to post different feeds to different channels, you have to run several instances.

Maybe I will change that, later.

Bye,
Markus
