### ISSUE TITLE
Cannot fetch from a specific feed with only sketchy error log message

### ISSUE THREAD

**Issue by axelrose** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#9]
Moin,

I have a problem with a specific feed from a TeamCity build server it seems. (All is fine with a different Rss feed).

```
feeds = [RssFeed('Failed TeamCity Builds', 'https://user:pass@build-server/httpAuth/feed.html?buildTypeId=bt3&itemsType=builds&buildStatus=failed&userKey=user',
                 'https://build-server/img/icons/TeamCity32@2x.png', 'Failed Builds', 'failed-teamcity-builds',
                  True, True, True, True)
         ]
```

I verified with an external RSS-Reader (Vienna) and with cURL that the URL returns valid results.

How can I get closer to this?

I tried first to improve the logging a bit
```
    FORMAT = '%(asctime)-15s - %(message)s'
    logging.basicConfig(stream=sys.stderr, level=logging.DEBUG, format=FORMAT)
```
and
```
            except:
                logging.critical('Error fetching feed.' + feed.Url)
```

But I'm still clueless since I now get in /var/log/myRssFeed.err.log:
```2016-04-23 07:10:19,697 - Error fetching feed: https://user:pass@build-server/httpAuth/feed.html?buildTypeId=bt3&itemsType=builds&buildStatus=failed&userKey=user```

Thanks for your time!

**Comment by dbanck** [comment]
Has `build-server` (I guess you've replaced the original url) a valid DNS record? Or is it an internal host the Mattermost server might not be able to resolve?

Since the URL contains `https`, are you using a valid SSL certificate or a self-signed one?

**Comment by axelrose** [comment]
DNS and SSL certicate handling should be correct.

I cross checked with ```nslookup```and by accessing the original URL from the command line with ```curl -k https://build-server/path```. (It is indeed a self-signed certificate)

settings.py has ```verify_cert = False```set.

**Comment by dbanck** [comment]
Okay, let's log the actual exception. Try to modify your exception logging to something like this:

    except Exception as e:
                logging.exception("Error fetching feed")

**Comment by axelrose** [comment]
Nothing new:
```
$ env/bin/python feedfetcher.py
2016-04-23 17:46:46,696 - Error fetching feed
```

I attached my _feetfetcher.py_ version. Perhaps I misunderstood the patching instruction.

Thanks a lot! 

[feedfetcher.py.zip](https://github.com/bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost/files/233020/feedfetcher.py.zip)

**Comment by axelrose** [comment]
I changed the except code to:
```
            except Exception as e:
                logging.critical('Error fetching feed')
                logging.exception(e)
                continue
```

and now have something more meaningful:
```
$ env/bin/python feedfetcher.py
2016-04-24 00:16:12,323 - Error fetching feed
2016-04-24 00:16:12,323 - list index out of range
Traceback (most recent call last):
  File "feedfetcher.py", line 58, in <module>
    feed.NewTitle = d['entries'][0]['title']
IndexError: list index out of range
```
This means in my understanding that the parsing result is different than expected. I'll try to check more details later.

**Comment by axelrose** [comment]
Solved.
The verify_cert configuration was never used. My feed was https.
Correction put into a new pull request.
Thanks for having patience with me :)

**Comment by dbanck** [comment]
Nice catch! Thank you, for your pull request.

I'll have a more detailed look at it soon.
